logging:
  level:
    org.springframework.cloud.task: INFO
    
spring:
  application:
    name: youtube-service
  datasource:
    url: "${DATASOURCE_URL:}"
    username: "${DATASOURCE_USERNAME:}"
    password: "${DATASOURCE_PASSWORD:}"
  sql:
    init:
      mode: always